server:
  port: 8011
  servlet:
    context-path: /dispatch

spring:
  profiles:
    active: local
  application:
    name: shield-dispatch
  config:
    import: optional:configserver:http://localhost:8888